### ISSUE TITLE
Clarify install instructions

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/rail_attic#108]
A new RAIL user had some difficulties getting everything to install with `pip install .[all]` and `python setup.py install`, I believe it was due to an out-of-date setuptools version, which does not install qp and DESC_BPZ from the specified GitHub repos.  We discussed it and the decision was to add more clarifying text to the README.md in case of other difficulties in install.  Not sure if bringing back the requirements.txt, I can look into auto-generating the requirements.txt file.

**Comment by jfcrenshaw** [comment]
Was this issue  addressed by #109? If so, we should link it and close this issue

**Comment by sschmidt23** [comment]
it was, I forgot to link the PR to the issue, closing now.
