### ISSUE TITLE
Add a new degrader to model magnitude error for extended sources

### ISSUE THREAD

**Issue by yanzastro** [LSSTDESC/rail_attic#131]
The current `LSSTErrorModel` only deals with point sources. We'll add a new module to deal with extended sources with finite aperture sizes.

The aperture sizes are calculated with two models:
1. the model from https://arxiv.org/abs/1902.11265, that is, to assume the magnitude to be measured as Kron-like elliptical aperture magnitude;
2. the Gaussian Aperture and PSF model from https://arxiv.org/abs/1902.11265, that is, to assume the magnitude to be measured as GAaP magnitude.

This is part of the GCCL in-kind contribution.

**Comment by yanzastro** [comment]
For extended sources error, there needs to be the major and minor length in the input table. Should we change the example flow to include them as two additional columns?

**Comment by aimalz** [comment]
@jfcrenshaw and I started but failed to finish refactoring creation to add in more flexibility, including for the columns, so we should wrap up #189 ASAP in order to address @yanzastro's question above.
