### ISSUE TITLE
Add placeholder BPZ inform stage

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/rail_attic#146]
not yet functional, but to match the pattern of the other algorithms, we should include the stage with just a `pass` for now.

**Comment by eacharles** [comment]
Do we really want a stage that seems to be doing something but isn't?

Maybe a `raise NotImplementedError("You can't actually Inform BPZ, but you can safely remove this stage from your pipeline")`

**Comment by sschmidt23** [comment]
That is a better solution, good idea.

**Comment by aimalz** [comment]
It looks like Delight also doesn't have one and needs one.

**Comment by sschmidt23** [comment]
TrainDelightPZ exists and works:
https://github.com/LSSTDESC/RAIL/blob/0bb8cf8af9ecac2f33d1cd33d87b7ab07519f0cb/rail/estimation/algos/delightPZ.py#L60

**Comment by aimalz** [comment]
Yikes, some estimators had `Train_*` and others had `Train*`, which I somehow missed when doing the renaming, thanks.

**Comment by aimalz** [comment]
I'm closing this in favor of #72, since the CatInformer placeholder is definitely done, but my impression is that some of its intended functionality still lives in its CatEstimator stage.
