### ISSUE TITLE
Merge summarization subpackage back into estimation

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/rail_attic#151]
Since stage superclasses are defined by the identity of their inputs and outputs, having a separate subpackage for each superclass will get out of hand as we add more estimators, summarizers, and hybrids, which themselves would end up duplicated across the estimation/summarization/variant subpackage directories. I'm going to merge the two directories ASAP so we don't bake this artificial distinction into v1 too hard.

**Comment by eacharles** [comment]
done via #152
