### ISSUE TITLE
Fresh conda env recommendation on install instructions

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/rail_attic#158]
Given all the dependencies in RAIL, and the propensity for out of date packages to break things, we discussed adding an explicit recommendation for a standalone CONDA environment to the install instructions.  We can also include a quick reminder of how to add this new environment to jupyter as well, as that will likely be a common use case.

**Comment by sschmidt23** [comment]
Also, though, is this a sign that we should be putting more explicit package version requirements in our setup.py?  E.g. out of date jax and jaxlib, if we put jax>[whatever version was throwing the error that Sylvie saw this morning]?  @jfcrenshaw do you have jax and jaxlib version requirements in pzflow?

**Comment by eacharles** [comment]
Done in #160
