### ISSUE TITLE
Newly added `qp` scipy Deprecation warning is causing mixmod test to fail for python3.7

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/rail_attic#161]
@eacharles added a deprecationWarning to mixmod_gen.py in `qp` that raises an error (and not a warning, i.e. it does not just happily chug along after printing warning text, it actually errors out) when a version of scipy<1.8.0 is being used.  As scipy stopped supporting python3.7 for scipy 1.8.0, this means that our python37 test of mixmod is always going to fail.  

I think that the error rather than warning is actually appropriate, as most mixmod parameterizations will happily chug through and give you incorrect answers if you have the older scipy, so this error may end up preventing unwitting propagation of errors.

But, we should either skip this test for python3.7 in our GitHub action, or update our action matrix of python versions to maybe python 3.8 and 3.9 rather than 3.7 and 3.8.  I think it comes down to how much we want to test/support python 3.7 with RAIL, knowing that some further scipy bugs could crop up, given the heavy scipy usage in qp.

**Comment by sschmidt23** [comment]
For right now I'm just putting in a pytest.mark.skipif to skip the mixmod test if scipy is <1.8, though I'll also add python 3.9 to our matrix.

**Comment by eacharles** [comment]
Done in #162
