### ISSUE TITLE
PDF creation and persistence need to be abstracted away

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/rail_attic#17]
In order to be able to choose among several persistence schemes, we probably need to abstract what goes into the `pz_pdf` attribute of an estimator instance.

**Comment by aimalz** [comment]
I would broaden this issue to include reworking (and renaming) `utils.py` to include all the i/o functionality (including any calls to [`qp`](https://github.com/LSSTDESC/qp)) so the `Creator`, `Estimator`, and `Evaluator` classes never need to be changed when we inevitably augment the formats as the kinds of inputs and outputs of these classes inherently become more sophisticated as `rail` develops.  Sound reasonable?

**Comment by johannct** [comment]
my next focus starting net week

**Comment by johannct** [comment]
redundant with #33 now
