### ISSUE TITLE
Bootstrap errors on the redshift distributions

### ISSUE THREAD

**Issue by sjoudaki** [LSSTDESC/rail_attic#173]
As discussed in today's RAIL tag up, it would be useful for us to provide errors on the n(z) that we obtain from the stacking and DIR methods as part of the STAR challenge. This could be in the form of a large number of bootstrap realizations of the n(z) consistent with past approaches in the literature (e.g. [KiDS-450](https://arxiv.org/pdf/1606.05338.pdf)). 

@eacharles @sschmidt23 @aimalz

**Comment by sjoudaki** [comment]
@eacharles noted that qp can moreover allow the user to obtain the error on the mean n(z) in each tomographic bin from these bootstrap realizations. @jlvdb do you know if this is how the mean errors were obtained in KV450?

**Comment by jlvdb** [comment]
In KV450 I think we got the DIR uncertainties by drawing random samples from the training catalogue.
Starting from the SOM, we used mock data to generate different lines of sight to compute the uncertainty on the recovered mean redshift. For the CCs we use spatial regions to compute bootstrap realisations of the measured correlation functions (directly implemented in yet_another_wizz).
