### ISSUE TITLE
Adding FitsHandle and unit testing

### ISSUE THREAD

**Issue by torluca** [LSSTDESC/rail_attic#176]
Adding the class FitsHanlde in rail/core/data.py and unit test for it.

**Comment by torluca** [comment]
Class and unit test added. I created a merge request to merge the issue branch with the main branch.

**Comment by eacharles** [comment]
Done in #178

**Comment by torluca** [comment]
Thank you! Do I have to remove the issue branch as well?

**Comment by eacharles** [comment]
You can if you want.    Otherwise I suspect it will stick around till someone clean those up at some point.

-e
