### ISSUE TITLE
help(RailStage)

### ISSUE THREAD

**Issue by jlvdb** [LSSTDESC/rail_attic#190]
`RailStage` and subclasses thereof produce a `KeyError` when running the python `help()` function:

> ---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> /home/janluca/dev/RAIL/RAIL/examples/core/hyperbolic_magnitude_test.ipynb Cell 8' in <cell line: 1>()
> ----> [1](vscode-notebook-cell:/home/janluca/dev/RAIL/RAIL/examples/core/hyperbolic_magnitude_test.ipynb#ch0000017?line=0) help(rail.core.RailStage)
> 
> File ~/anaconda3/envs/rail/lib/python3.8/_sitebuiltins.py:103, in _Helper.__call__(self, *args, **kwds)
>     [101](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/_sitebuiltins.py?line=100) def __call__(self, *args, **kwds):
>     [102](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/_sitebuiltins.py?line=101)     import pydoc
> --> [103](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/_sitebuiltins.py?line=102)     return pydoc.help(*args, **kwds)
> 
> File ~/anaconda3/envs/rail/lib/python3.8/pydoc.py:1909, in Helper.__call__(self, request)
>    [1907](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1906) def __call__(self, request=_GoInteractive):
>    [1908](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1907)     if request is not self._GoInteractive:
> -> [1909](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1908)         self.help(request)
>    [1910](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1909)     else:
>    [1911](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1910)         self.intro()
> 
> File ~/anaconda3/envs/rail/lib/python3.8/pydoc.py:1968, in Helper.help(self, request)
>    [1966](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1965)     else: doc(str, 'Help on %s:', output=self._output)
>    [1967](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1966) elif isinstance(request, Helper): self()
> -> [1968](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1967) else: doc(request, 'Help on %s:', output=self._output)
>    [1969](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1968) self.output.write('\n')
> 
> File ~/anaconda3/envs/rail/lib/python3.8/pydoc.py:1688, in doc(thing, title, forceload, output)
>    [1686](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1685) try:
>    [1687](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1686)     if output is None:
> -> [1688](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1687)         pager(render_doc(thing, title, forceload))
>    [1689](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1688)     else:
>    [1690](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1689)         output.write(render_doc(thing, title, forceload, plaintext))
> 
> File ~/anaconda3/envs/rail/lib/python3.8/pydoc.py:1681, in render_doc(thing, title, forceload, renderer)
>    [1679](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1678)     object = type(object)
>    [1680](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1679)     desc += ' object'
> -> [1681](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1680) return title % desc + '\n\n' + renderer.document(object, name)
> 
> File ~/anaconda3/envs/rail/lib/python3.8/pydoc.py:381, in Doc.document(self, object, name, *args)
>     [379](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=378) try:
>     [380](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=379)     if inspect.ismodule(object): return self.docmodule(*args)
> --> [381](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=380)     if inspect.isclass(object): return self.docclass(*args)
>     [382](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=381)     if inspect.isroutine(object): return self.docroutine(*args)
>     [383](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=382) except AttributeError:
> 
> File ~/anaconda3/envs/rail/lib/python3.8/pydoc.py:1325, in TextDoc.docclass(self, object, name, mod, *ignored)
>    [1320](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1319)             push(self.docother(obj, name, mod, maxlen=70, doc=doc) +
>    [1321](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1320)                  '\n')
>    [1322](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1321)     return attrs
>    [1324](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1323) attrs = [(name, kind, cls, value)
> -> [1325](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1324)          for name, kind, cls, value in classify_class_attrs(object)
>    [1326](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1325)          if visiblename(name, obj=object)]
>    [1328](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1327) while attrs:
>    [1329](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=1328)     if mro:
> 
> File ~/anaconda3/envs/rail/lib/python3.8/pydoc.py:204, in classify_class_attrs(object)
>     [202](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=201) """Wrap inspect.classify_class_attrs, with fixup for data descriptors."""
>     [203](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=202) results = []
> --> [204](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=203) for (name, kind, cls, value) in inspect.classify_class_attrs(object):
>     [205](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=204)     if inspect.isdatadescriptor(value):
>     [206](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/pydoc.py?line=205)         kind = 'data descriptor'
> 
> File ~/anaconda3/envs/rail/lib/python3.8/inspect.py:435, in classify_class_attrs(cls)
>     [433](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/inspect.py?line=432)     pass
>     [434](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/inspect.py?line=433) else:
> --> [435](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/inspect.py?line=434)     homecls = getattr(get_obj, "__objclass__", homecls)
>     [436](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/inspect.py?line=435)     if homecls not in class_bases:
>     [437](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/inspect.py?line=436)         # if the resulting object does not live somewhere in the
>     [438](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/inspect.py?line=437)         # mro, drop it and search the mro manually
>     [439](file:///home/janluca/anaconda3/envs/rail/lib/python3.8/inspect.py?line=438)         homecls = None
> 
> File ~/dev/RAIL/RAIL/rail/core/data.py:384, in DataStore.__getattr__(self, key)
>     [382](file:///home/janluca/dev/RAIL/RAIL/rail/core/data.py?line=381) def __getattr__(self, key):
>     [383](file:///home/janluca/dev/RAIL/RAIL/rail/core/data.py?line=382)     """ Allow attribute-like parameter access """
> --> [384](file:///home/janluca/dev/RAIL/RAIL/rail/core/data.py?line=383)     return self.__getitem__(key)
> 
> KeyError: '__objclass__'

**Comment by eacharles** [comment]
fixed in #194
