### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/rail_attic#2]
We can use the config files from [CLMM](https://github.com/LSSTDESC/CLMM) as a template.

EDIT: This issue can be closed when:
- [x] Travis is connected to this repo
- [x] There is a `tests` directory with a dummy test
- [x] Coveralls is connected to this repo

**Comment by johannct** [comment]
note: @sschmidt23  seems to propose actions rather barebone travis.... I presume this is a gcr-catalogs versus clmm for instance.

**Comment by johannct** [comment]
we went for github actions rather than travis, but nevertheless the first bullet is checked. coveralls seems simpler to set up within travis than gh/actions though.

**Comment by sschmidt23** [comment]
Not sure how helpful it is as I haven't used coveralls and I don't know what `black` is, but I saw this morning that  Blending Toolkit has coveralls set up, so maybe we could use their actions file as an example to help us get things running?
https://github.com/LSSTDESC/BlendingToolKit/blob/multi-resolution/.github/workflows/config.yml

**Comment by johannct** [comment]
8157f19 adds a basic coverage action
