### ISSUE TITLE
Unpin the numpy version

### ISSUE THREAD

**Issue by jfcrenshaw** [LSSTDESC/rail_attic#208]
I pinned `numpy<1.23` due to bugs and incompatibilities with jax (see [this comment](https://github.com/LSSTDESC/RAIL/pull/207#issuecomment-1165959634)). Jax and numpy are working on fixes which should be published on PyPI soon. In a week or two, we should test un-pinning numpy.

**Comment by sschmidt23** [comment]
closed by #235
