### ISSUE TITLE
Add a simple SOM summarizer

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/rail_attic#225]
The NZDir summarizer is nice, but it still slightly bugs me that it is "blind" to photometric galaxies that are not neighbors to any of the training galaxies with spec-z, i.e. you can have areas of color^N space that are not covered by your training data but do contain photometric data, and if that area of color space has a different redshift distribution than the other areas in the tomographic bin it can induce bias.
Also, I just want to experiment with SOMs a bit, and checking SOM cell occupancy of both the photometric and spectroscopic training sets will identify SOM cells not covered by training, those cells can be studied and excluded from tomographic bin constructions once identified.  It may also be possible to use similar machinery to come up with "weights" for the spec-z dataset to try to "re-balance" training sets to better match photometric datasets in the future (this is really why I was looking in to SOMSs
)
I found a very lightweight SOM package called `minisom` that depends only on numpy and is pip installable, I wrote up something similar to NZDir but using a SOM rather than neighbors as an additional summarizer for RAIL.

NOTE: this is in no way equivalent to the full DES-like multi-tier SOM, this is much more simple than that.

**Comment by johannct** [comment]
what is the status of getting the DES SOM in? I seem to remember that it was envisioned (but I have been disconnected with the RAIL effort for a while now....)

**Comment by sschmidt23** [comment]
@jlvdb will be working on the DES SOM in the near future.

**Comment by jlvdb** [comment]
Our plan was that I work on the CCs while @yanzastro starts (re)implements the original SOM code in python.

**Comment by yanzastro** [comment]
Yes I'll work on it after I finish spec selection. I still don't know whish SOM code to use but `minisom` might be a good start

**Comment by sschmidt23** [comment]
minisom is pretty minimal, I think that it can only generate 2D rectangular SOM's, I think, but that might be good enough for our purposes.  Here's the GitHub repo:
https://github.com/JustGlowing/minisom

**Comment by johannct** [comment]
We can get in touch with Agnes Ferté (now at SLAC) if that can help
