### ISSUE TITLE
Establishing a directory structure for RAIL projects

### ISSUE THREAD

**Issue by jfcrenshaw** [LSSTDESC/rail_attic#231]
Directory structure: `rail_pipelines/{study_name}/{config_name}/{data_type}/{data_subtype}`

`rail_pipelines` contains:
- global README
- `ref_cats`
- directories corresponding to different studies

The directory for each study contains:
- a README that describes the study
- directories corresponding to different configurations

the configuration directories contain:
- the 2 config files
- the directories corresponding to `{data_type}`

The `data_types` are:
- `catalogs`
- `models`
- `pdfs`
- `metrics`

The `data_subtypes` depend on the `data_type`.
The subtypes for `catalogs` are:
- `created_cats`
- `degraded_cats`
- etc

The subtypes for `models` are:
- `creators`
- `degraders`
- `estimators`
- `summarizers`
- `evaluators`

The directory structure under each study do not need to be pre-created by the user, but will instead be created and populated by the ceci pipeline as it runs. However, we need to make sure that the user creates file names that obey the structure we want. In order to aid this, we will create a `NameFactory` (issue #230) class that will generate the paths to files you want to save.

**Comment by eacharles** [comment]
Done in rail_pipelines
