### ISSUE TITLE
Simplify pip install options

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/rail_attic#245]
When things were more complicated with Delight, FZBoost, etc... we created install options for .[base], .[all], etc..., now that we've moved those packages out we should simplify this a bit and change the default install to grab all necessary packages (a few like pzflow used by PZFlowPDF are not installed by default with a simple `pip install pz-rail`).

We can discuss a bit whether we want any remaining options, or whether we should basically just have everything in pip install .[all] basically be the default option.

**Comment by johannct** [comment]
My natural tendency is to think, at least as a default, of [all] as being base + test + doc, so that .[all] ensures that tests can be run and doc can be regenerated. Of course things get more complex when there is need to deal with external files, optional dependencies for [base], etc...
