### ISSUE TITLE
Implement somoclu as a new SOM summarizer

### ISSUE THREAD

**Issue by yanzastro** [LSSTDESC/rail_attic#252]
somoclu (https://somoclu.readthedocs.io/en/stable/) seems to be a great SOM package with parallelization. I'll try to implement it into RAIL

**Comment by johannct** [comment]
isn't there a case to move up the question of a SOM implementation to a larger audience? DESC software stack could benefit from a choice of SOM code more largely than its usage in RAIL..... and this would allow to avoid switching from one implementation to another without a proper decision process. My 2 cents

**Comment by yanzastro** [comment]
I guess SOM itself is not a very complicated algorithm, and the existing SOM packages (including minisom and somoclu) can do a pretty comprehensive job of training and analyzing pre-trained SOM. What matters is the subsequent analyses according to different tasks, which I think is not portable between different tasks. But I agree with you that we should discuss with people from other WGs if we should use the same SOM package or if it's necessary to develop our own SOM package.
