### ISSUE TITLE
Request to rename sklearn dependency to scikit-learn

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/rail_attic#257]
Use scikit-learn rather than sklearn in the toml file. The official package name is scikit-learn and in conda-forge, that's the name that is available, not sklearn. See: https://pypi.org/project/sklearn/  that is a dummy pypi project
Why does it matter? Because if I wanted to set up an environment that uses the conda-forge scikit-learn and then install RAIL using pip - it goes off and installs the dummpy sklearn pypi package which is confusing.

**Comment by sschmidt23** [comment]
closed by #258
