### ISSUE TITLE
RailStage.input_iterator reads all the data in before iterating through it

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/rail_attic#265]
Unless I've misunderstood this, the method RailStage.input_iterator appears to read all the data in from a file before iterating through it:
    https://github.com/LSSTDESC/RAIL/blob/d27b3fbf6ab90c1b9cb7c530e63af298932e2859/src/rail/core/stage.py#L329

This defeats the whole point of iterating through the data, which is to avoid loading it all into memory at once. I'm trying to run a basic pipeline in parallel on CosmoDC2 data and this is causing an out-of-memory crash when I try to use multiple cores.

**Comment by eacharles** [comment]
Yup, you are right.  I'll fix this.

**Comment by eacharles** [comment]
Fixed in #267
