### ISSUE TITLE
Galaxy population modelling components in RAIL

### ISSUE THREAD

**Issue by torluca** [LSSTDESC/rail_attic#269]
The aim is to implement in RAIL to creation the possibility of generating galaxy samples from a library of galaxy modelling components. The latter are going to be implemented in a separate light-weight package that RAIL imports.

**Comment by aimalz** [comment]
Just a note that the guts of [this](https://github.com/LSSTDESC/RAIL/tree/issue/269/gal_pop_model_components/src/rail/creation), and [rail_fsps](https://github.com/LSSTDESC/rail_fsps/tree/main/src/rail/creation) and the plans for #268, can be made compatible with the `creation.engines` structure so users can take advantage of the common interface when doing side-by-side comparisons of ways to forward model mock photometry.

**Comment by torluca** [comment]
I restructured this code to make it compatible with creation.engines. Polishing and planning to git push this week.

**Comment by torluca** [comment]
Following Alex's and Eric's suggestions, I moved the restructured the external package following the DESC guidelines. The package is now hosted at https://github.com/LSSTDESC/rail_lib_gp_comp
Furthermore, the modelling components in RAIL are called via a modeler and a generator classes.

**Comment by aimalz** [comment]
I think we forgot to close this issue -- thanks @torluca for getting this done!
