### ISSUE TITLE
Failed to run flexzboost in goldenspike notebok.

### ISSUE THREAD

**Issue by gschwend** [LSSTDESC/rail_attic#271]
Hi all, 
I removed and reinstalled RAIL after the reorganization and now I am reviewing the example notebooks to recap and learn the new features that appeared since the last time I used it. I got a failure in the goldenspike notebook, so I think it is worth letting you know.  

I created a new conda env for RAIL and installed both pz-rail-bpz and pz-rail-flexzboost separately, as recommended on the readthedocs page. It looks like bpz is working okay, but flexzboost is not. I got an error on `inform_fzboost.inform(train_data)`, apparently the notebook didn't find the module. 

>  File ~/opt/anaconda3/envs/rail/lib/python3.10/site-packages/rail/estimation/algos/flexzboost.py:141, in Inform_FZBoost.run(self)
>         138 def run(self):
>         139     """Train flexzboost model model
>         140     """
>  --> 141     import flexcode
>         142     from flexcode.regression_models import XGBoost
>         143     from flexcode.loss_functions import cde_loss
> ModuleNotFoundError: No module named 'flexcode'
  
Should I do some extra step after installing the pz-rail-flexzboost?  
Thanks

**Comment by gschwend** [comment]
And about bpz, actually, it didn't work on the first attempt. I had to create a new dir called configs inside src/rail/examples/estimation/ and copy the file test_bpz.columns in there.

**Comment by sschmidt23** [comment]
There's a problem in the current rail_flexzboost where the new pyproject.toml is not pip installing the updated FlexCode from requirements.txt, I meant to create an issue for this but forgot, I'll create the issue in the rail_flexzboost repo now. 

The workaround is to just install the requirement by hand, if you cloned the rail_flexzboost repo you can just do a `pip install -r requirements.txt` from the rail_flexzboost directory, or just do a 
`pip install git+https://github.com/lee-group-cmu/FlexCode` to grab FlexCode 0.2

**Comment by gschwend** [comment]
Thanks @sschmidt23 !
