### ISSUE TITLE
MPI run with small datasets causes a crash

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/rail_attic#275]
At least on cori, running  an estimator via a batch job where you have a total number of galaxies that is smaller than the chunk size times the number of processors that you are running on causes a crash, as it sets up N processes, but at least one of those does not receive any data from the iterator, but it still tries to run `finalize_write` and does not end up producing an output file.  A portion of the error message:

```
    PipelineStage.main()
  File "/global/homes/s/schmidt9/.local/cori/3.9-anaconda-2021.11/lib/python3.9/site-packages/ceci/stage.py", line 469, in main
    stage.execute(args)
  File "/global/homes/s/schmidt9/.local/cori/3.9-anaconda-2021.11/lib/python3.9/site-packages/ceci/stage.py", line 604, in execute
    self._output_handle.finalize_write()
AttributeError: 'NoneType' object has no attribute 'finalize_write'
```

**Comment by sschmidt23** [comment]
This came about as I was running FlexZBoost on files containing the data for each of the 166 run2.2i_dr6_v2 DC2 tracts, while most of the tracts have ~1 million objects per file, a couple at the edges have like 78-10,000.
If I set `nprocess: 1` and `threads_per_process: 1` (i.e. run on only one processor) then the script now runs successfully.  

We should add some sort of check on the number of input objects vs number of processes, though, maybe scale it back to a smaller number of needed processes?

**Comment by eacharles** [comment]
The easiest solution is probably just to treat the empty chunks as no-ops and just make sure they don’t crash stuff.

-e

**Comment by drewoldag** [comment]
This sounds like an edge case that a user might run into that should be addressed before releasing v1. What are your thoughts @sschmidt23 @eacharles?

**Comment by sschmidt23** [comment]
Did @joselotl say that he was looking into this at the tag-up last week?  I think so but I may be misremembering.  I agree that it's something that we should take care of before v1.

**Comment by joselotl** [comment]
Yes. I stumbled upon this issue and I can solve it. I have time to do it
next week because right now I'm in holiday

**Comment by sschmidt23** [comment]
Having it fixed next week would be great, thanks Josue.
