### ISSUE TITLE
Deprecate Brier and PIT metrics

### ISSUE THREAD

**Issue by drewoldag** [LSSTDESC/rail_attic#282]
Add deprecation warning messages to Brier and PIT metric classes. Update the dependency on qp-prob to the newest version that includes the Brier and PIT metrics. Update references to Brier and PIT in RAIL to use the qp-prob implementation. Deprecate/deactivate unittests for Brier and PIT in RAIL.

**Comment by aimalz** [comment]
Closed by #283
