### ISSUE TITLE
Autodoc to formalize documentation

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/rail_attic#34]
The title says it all! ~~I'm going to steal the sphinx setup from [CLMM](https://github.com/LSSTDESC/CLMM) as a template to get started, but anyone else is welcome to jump in on this.~~ Yikes, that's got more bells and whistles than we need at this stage. @sjoudaki will be taking it from here and starting from something simpler like [qp](https://github.com/aimalz/qp).

**Comment by johannct** [comment]
I add here that when ready to tag RAIL, autodoc needs to be ready, but also README.md will need to be updated, especially with detailed mentions of how to build and what are the different required and optional packages. Pinging @sschmidt23 on this

**Comment by aimalz** [comment]
#82/#83 address the final comment here, so I'm going to close this issue in light of #53.
