### ISSUE TITLE
Check somoclu/pip 23.1 installation on ancillary packages

### ISSUE THREAD

**Issue by olivialynn** [LSSTDESC/rail_attic#344]
I ran into the same error as #333 when working with bpz's CI, and was able to bypass it by adding `pip install wheel numpy` in the CI for my branch there. ([failed install in job](https://github.com/OliviaLynn/rail_bpz/actions/runs/4808550187) w/out this addition, [successful](https://github.com/OliviaLynn/rail_bpz/actions/runs/4808589297/jobs/8558758137) w/)

This change may need to be copied to all ancillary RAIL packages. 

I'm trying to wrap some things up before further investigating, but putting this here as a reminder.

**Comment by eacharles** [comment]
Fixed for somo stuff.  Added elsewhere out of an abundance of caution
