### ISSUE TITLE
Error model for the creation module

### ISSUE THREAD

**Issue by jfcrenshaw** [LSSTDESC/rail_attic#35]
creator.py has the ability to include photometric errors using Eq 5 from https://arxiv.org/pdf/0805.2366.pdf
I need to finalize how this is handled, including flagging magnitudes beyond the 5-sigma limit.

Once that is done, I need to include error convolution in the posterior calculations. I have a way to do this analytically, and have it implemented, just need to finalize how to integrate it in the normalizing flow framework.

**Comment by johannct** [comment]
@jfcrenshaw  any chance this issue is going to be revived soon? Is there any news about it?

**Comment by jfcrenshaw** [comment]
Picking this back up now. 

Note that error convolution isn't analytic anymore; it is done via sampling. But that is okay, as photometric errors aren't Gaussian anyway, and convolving via sampling allows us to handle non-Gaussian errors properly.

pzflow can also now marginalize over missing bands when calculating posteriors (although this can get computationally expensive if you have galaxies with multiple missing bands).
