### ISSUE TITLE
Moving data

### ISSUE THREAD

**Issue by olivialynn** [LSSTDESC/rail_attic#356]
Returning to the question of "does data really need to live inside src/rail?" 

I've done my best to research data storage best practices for python packages, but have not found anything that says it must be kept right next to the code for a case like RAIL (in which our data, in theory, is only used by notebooks and tests).

I will be exploring this to figure out if we really can move the data. (I feel like I've encountered one place where data was used by actual rail code in a way that surprised me, but I don't remember off the top of my head.)

Let me know if you have thoughts or further information on this.

**Comment by eacharles** [comment]
In short, I don’t think  it _has_ to live there, but I wasted a few hours trying to setup the pyproject.toml file to pick it up correctly if it wasn’t there and figured i had better things to do with my time.

If you can come up with a way to get it to work, say in a top level ‘data’ directory, that would be great.

-e

**Comment by aimalz** [comment]
I'm going to close this issue because LSSTDESC/rail_hub#26 contains the specifics of where files are being moved to and encompasses propagating the changes through the tests and demos.
