### ISSUE TITLE
Standardize estimator parameter names

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/rail_attic#358]
Running some tests with HSC data, Eric noticed that I was a bit loose with some of the common parameter names in a few estimation stages, e.g. `column_names` in Inform_KNearNeigh been the equivalent of `bands` in most of the other estimators, we should make these more standard for a v1 RAIL release.  There is infrastructure for propagating this info across multiple stages/estimators already implemented via the `rail.core.common_params` option `SHARED_PARAMS`, so we might want to switch the estimators to use `SHARED_PARAMS` and set this in just one place.

**Comment by eacharles** [comment]
Done a while back.
