### ISSUE TITLE
Modify estimation ingest to remove assumption that we are reading in from a file

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/rail_attic#48]
Current RAIL/estimation is coded such that it assumes we are reading from an hdf5 file.  We should separate the read-in and instead have the data ingest as a separate stage and feed Estimator dictionaries for the test and (optional) training data.

**Comment by aimalz** [comment]
I think the scope of this could be generalized to moving i/o to a standalone module shared across creation, estimation, and evaluation. Then we'd guarantee their mutual consistency no matter how many times we refactor the formats (probably unavoidable given XWG dependencies, etc.), and those refactorings would only have to touch one file. Thoughts?

**Comment by sschmidt23** [comment]
closed by #60
