### ISSUE TITLE
Registering a new algorithm in Rail

### ISSUE THREAD

**Issue by sylvielsstfr** [LSSTDESC/rail_attic#50]
I am trying to add a new algo.
I have created a config file and a python file but apparently the new algo is not detected by rail:

/Users/dagoret/MacOSX/GitHub/LSST/RAIL/examples>python main.py configs/delightPZ.yaml 
Found classifier FZBoost
Found classifier randomPZ
Found classifier simpleNN
Found classifier trainZ
Traceback (most recent call last):
  File "main.py", line 29, in main
    Estimator._find_subclass(name)
  File "/Users/dagoret/.local/lib/python3.7/site-packages/rail-0.1.dev0-py3.7.egg/rail/estimation/estimator.py", line 23, in _find_subclass
    return cls._subclasses[name]
KeyError: 'delightPZ'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 60, in <module>
    main(sys.argv)
  File "main.py", line 31, in main
    raise ValueError(f"Class name {name} for PZ code is not defined")
ValueError: Class name delightPZ for PZ code is not defined

Where should I declare this new module ?

Many thanks.

Sylvie

**Comment by johannct** [comment]
Do you have a code under estimation/algos/ that implements a class named delightPZ?

**Comment by sschmidt23** [comment]
As Johann said, if you have a file that is in the estimation/algos directory, then the estimation/__init__.py, which has `from .algos import *` should import the class.  The class should have an init similar to those for FZBoost or one of the other algorithms, and should also contain functions inform and estimate as well.

**Comment by sylvielsstfr** [comment]
OK thanks for the explanation. It works now.

**Comment by johannct** [comment]
dont hesitate to push to a branch to share development. Let us know when this can be closed.

**Comment by sylvielsstfr** [comment]
OK for the moment the branch delight has been pushed and this issue can be closed.

**Comment by johannct** [comment]
ok closing, do not hesitate to open a PR when you feel that ti is worth having external eyes on it. It does not need to be pristine to be in a draft PR
