### ISSUE TITLE
GPz

### ISSUE THREAD

**Issue by pwhatfield** [LSSTDESC/rail_attic#55]
Have discussed this with some of the organisers, but just putting it here if that is helpful for people, but we are hoping to incorporate GPz into RAIL, Nijin Thykkathu working on a SWIG python wrapper for the C++ version to this end, still a work in progress
https://github.com/cschreib/PHZ_GPz

**Comment by sschmidt23** [comment]
closed via the creation of https://github.com/LSSTDESC/rail_gpz_v1
