### ISSUE TITLE
Incorporate CDE diagnostics as evaluators

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/rail_attic#63]
This is just a reminder for us to make sure [the new CDE diagnostics](https://github.com/zhao-david/CDE-diagnostics) make it into RAIL.evaluation at some point. (The awareness of photometry means this issue is for RAIL rather than qp.)

**Comment by johannct** [comment]
I'd be keen on doing it, if nobody has a strong push to implement it. @Gschwend @aimalz  @sschmidt23 ?

**Comment by aimalz** [comment]
Thanks @johannct for volunteering! It'd be best to wait until after #4 is closed because the API for evaluators isn't quite finalized, but, yes, it'll be next on the list.

**Comment by eacharles** [comment]
Somewhere along the way this got done.
