### ISSUE TITLE
Organization of examples and notebooks

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/rail_attic#66]
As referenced in draft PR #61 the examples folder is now a bit haphazard, as it's grown around the original estimation-centric main.py.  The docs/notebooks notebooks can also be consolidated in examples.  Creating separate folders for each major branch, `creation/`, `estimation/`, and `evaluation/`, and storing both command-line and jupyter demos there should make things easier to deal with.

**Comment by johannct** [comment]
are you sure it is legit to split the demos and examples nb/scripts by branches? What about examples and demos that exercise more than one branch?

**Comment by sschmidt23** [comment]
would they be in an "end_to_end" directory, maybe?  Or "golden_spike" if we're being less literal?

**Comment by sschmidt23** [comment]
"pipelines" actually seems like a good name for such examples, I'll add a directory with that name as well.

**Comment by johannct** [comment]
in CLMM a distinction is drawn between examples and demo : I did not check there but in my mind demo would refer to more extensive and complete use cases, so perhaps what you were tempted to call pipelines. If we can have homogeneous "look n feel" for our readthedocs within DESC it would be nice, though I do not mean to enforce it. (and true : the way it is rendered in the doc does not have to be exactly the way it is provided in the repo)

**Comment by sschmidt23** [comment]
This is addressed by #67 though I'm not sure on whether this is the final form that we want or not (there was some debate on docs/notebook vs examples/[creation/estimation/evaluation], so I'll leave it open for now.

**Comment by aimalz** [comment]
Well, I think this can be closed now. If we want to reorganize again, we can make a new issue for it.
