### ISSUE TITLE
For golden spike release we need to document the items in the estimation/configs properly

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/rail_attic#71]
This should not rely on the fact that some if not all items are fields requested by external codes.

**Comment by sschmidt23** [comment]
What form do you see for this documentation?  Does it live in the code, or in a separate README file somewhere?

**Comment by johannct** [comment]
I'd vote for a separate Readme in the concerned dirs.

**Comment by sschmidt23** [comment]
I added README.md files to RAIL/estimation/algos and RAIL/examples/estimation that mentions that lists all of the necessary config params for each algorithm.  Wanted to add this before we bump to another tagged version.
