### ISSUE TITLE
Adding some Evaluation to the Demos

### ISSUE THREAD

**Issue by AngusWright** [LSSTDESC/rail_attic#75]
The notebook examples/demos are _awesome_! 🥳 

Can we add some basic evaluation to these demos, which also motivate the work we're doing here? I'm thinking of adding the PIT, for example, of the true PDFs that are simulated in [this document](https://github.com/LSSTDESC/RAIL/blob/master/examples/creation/basic-creation-demo.ipynb) ?

**Comment by aimalz** [comment]
Sorry for the delay @AngusWright! There are demos for evaluation in [the branch](https://github.com/LSSTDESC/RAIL/tree/issue/4/evaluation-baseline/examples/evaluation) for #4 right now, but I agree that it would be better if they used the output of the demos for the other subpackages. #54 has not yet been finalized (just waiting on unit tests), so you're welcome to make this change in its demo notebook. Interested?

EDIT: This issue can be closed when #54 is merged and #85 is closed.
