### ISSUE TITLE
Add code for catalog creation GAN

### ISSUE THREAD

**Issue by jbkalmbach** [LSSTDESC/rail_attic#8]
The `creation` module will use a GAN to create a densely populated space in the photometry-redshift space. The input will be a generic catalog and the output will feed into the interpolation code that will create "true" posteriors.

**Comment by aimalz** [comment]
Just to keep track of what was discussed on today's call, the next step here is to add in some evaluation of the GAN's performance.

**Comment by aimalz** [comment]
This has been replaced in [the branch](https://github.com/LSSTDESC/RAIL/tree/issue/7/creation-baseline) for #7 with a JAX-based interpolation.
