### ISSUE TITLE
Degradation after Creation?

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/rail_attic#91]
The degradation demo uses the NF of example data packaged with pzflow to make RAIL.Creator objects that are biased in known ways to a tunable degree relative to the input NF. However, the degradation code cannot accept an NF corresponding to a RAIL.Creator. I get that the issue is fundamental in that RAIL.Creator objects correspond to a conditional NF and the degraders only make sense for non-conditional NFs, but this seems like degrading from a RAIL.Creator is something important to have for the degraders to be useful, which I guess amounts to making it possible to have RAIL.Creator objects somehow output a non-conditional NF. Or is there another way to do this without modifying the RAIL.Creator objects?

**Comment by jfcrenshaw** [comment]
We discussed this during a tag-up a few weeks back.

I think this issue results from a misunderstanding of RAIL.Creator objects. The Flows we use in Creation are *not* conditional flows. They are regular flows that generate pandas DataFrames containing redshift+ugrizy. These DataFrames are then post-processed by degraders (e.g. a degrader might look at the DataFrame and throw out any objects with SNR < 5).

Let me know if I didn't actually address the issue/question here!
