### ISSUE TITLE
Add a pzflow photo-z estimator to the Estimation Module

### ISSUE THREAD

**Issue by jfcrenshaw** [LSSTDESC/rail_attic#94]
A Flow from pzflow can be used to estimate photo-z's. At some point, I want to add one of these to the Estimation Module, but it is currently low-priority.

**Comment by sschmidt23** [comment]
I added a simple pzflow-based estimator to the [issue/94/pzflow-estimator](https://github.com/LSSTDESC/RAIL/tree/issue/94%2Fpzflow-estimator) branch that ignores the photometric errors and only uses magnitude.  It also simply replaces non-detections in any band with the 1 sigma detection limits, we can add in a separate flow that could draw a sample from non-detects later.

Things work well, however, it appears that there are differences in the test values between the python3.7 and python3.8 branches (and the values that I get on my home machine vs the numbers produced by the ubuntu vm in the GitHub action).  We'll have to track down why these differences occur, it could be a random seed or something similar not being set.
